name: Stock APIs CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: |
          touch .env
          echo "${{ secrets.PROD_ENV_FILE }}" > .env
      - run: npm ci
      - run: pm2 list
      - run: pm2 restart all
