name: Stock APIs CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - run: |
          touch .env
          echo "${{ secrets.PROD_ENV_FILE }}" > .env
      - run: npm ci
      - run: pm2 list
      - run: pm2 restart all
