# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy On Test Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [self-hosted, aws-dev]

    steps:
    - uses: actions/checkout@v3
    - run: cp /home/ubuntu/actions-runner-stock/stock/secret/.env /home/ubuntu/actions-runner-stock/_work/stock-backend
    - run: npm i
    - run: pm2 list
    - run: pm2 restart all
